spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/chostagram
    username: root
    password: 9162
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace

custom:
  profileImg:
    path: '/Users/jodoil/Study/profile_imgs/'
  post:
    path: '/Users/jodoil/Study/uploads/'

